# Generated by Django 3.2.4 on 2021-06-13 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobileadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('user', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('Ordered', 'Ordered'), ('Cancelled', 'Cancelled'), ('Delivered', 'Delivered')], default='ordered', max_length=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobileadmin.product')),
            ],
        ),
    ]
